import type { LocalizedText, PartyItem } from './content'

export type PortfolioItem = Omit<PartyItem, 'category' | 'audience'> & {
  category: 'rental' | 'decoration' | 'pickup'
  audience: 'kids' | 'adults'
}

const item = (id: string, image: string, name: LocalizedText, description: LocalizedText, audience: PortfolioItem['audience']): PortfolioItem => ({ id, image, name, description, category: 'decoration', audience })

export const portfolioItems: PortfolioItem[] = [
  item('adults-newyear-silver', '/portfolio/adults-newyear-silver.jpg', { pt: 'Réveillon Prata', es: 'Año Nuevo Plateado', en: 'Silver New Year' }, { pt: 'Parede de lantejoulas prateadas, painel Happy New Year e balões cromados.', es: 'Pared de lentejuelas plateadas, panel Happy New Year y globos cromados.', en: 'Silver sequin wall, Happy New Year panel and chrome balloons.' }, 'adults'),
  item('adults-birthday-pink-gold', '/portfolio/adults-birthday-pink-gold.jpg', { pt: 'Aniversário Rosa e Dourado', es: 'Cumpleaños Rosa y Dorado', en: 'Pink & Gold Birthday' }, { pt: 'Painéis rosa e madeira, balões e arranjos florais.', es: 'Paneles rosa y madera, globos y arreglos florales.', en: 'Pink and wood panels, balloons and floral arrangements.' }, 'adults'),
  item('adults-birthday-snowwhite-red', '/portfolio/adults-birthday-snowwhite-red.jpg', { pt: 'Branca de Neve Vermelho e Dourado', es: 'Blancanieves Rojo y Dorado', en: 'Snow White Red & Gold' }, { pt: 'Parede de folhagem, bolo, espelho dourado e rosas vermelhas.', es: 'Pared de follaje, pastel, espejo dorado y rosas rojas.', en: 'Foliage wall, cake, gold mirror and red roses.' }, 'adults'),
  item('adults-birthday-pearl-gold', '/portfolio/adults-birthday-pearl-gold.jpg', { pt: 'Aniversário Pérola e Dourado', es: 'Cumpleaños Perla y Dorado', en: 'Pearl & Gold Birthday' }, { pt: 'Arco branco, balões pérola, pedestais dourados e flores.', es: 'Arco blanco, globos perlados, pedestales dorados y flores.', en: 'White arch, pearl balloons, gold pedestals and flowers.' }, 'adults'),
  item('adults-birthday-gold-white', '/portfolio/adults-birthday-gold-white.jpg', { pt: 'Aniversário Dourado e Branco', es: 'Cumpleaños Dorado y Blanco', en: 'Gold & White Birthday' }, { pt: 'Arco dourado, balões brancos e dourados e flores.', es: 'Arco dorado, globos blancos y dorados y flores.', en: 'Gold arch, white and gold balloons and flowers.' }, 'adults'),
  item('adults-birthday-green-gold', '/portfolio/adults-birthday-green-gold.jpg', { pt: 'Aniversário Verde e Dourado', es: 'Cumpleaños Verde y Dorado', en: 'Green & Gold Birthday' }, { pt: 'Painel bege, balões verdes, creme e dourados.', es: 'Panel beige, globos verdes, crema y dorados.', en: 'Beige panel, green, cream and gold balloons.' }, 'adults'),
  item('adults-birthday-pink-outdoor', '/portfolio/adults-birthday-pink-outdoor.jpg', { pt: 'Piquenique Rosa 18 Anos', es: 'Picnic Rosa 18 Años', en: 'Pink Picnic 18th Birthday' }, { pt: 'Mesa ao ar livre com almofadas, louças rosas e balões.', es: 'Mesa al aire libre con cojines, vajilla rosa y globos.', en: 'Outdoor table with cushions, pink tableware and balloons.' }, 'adults'),
  item('adults-elegant-red-gold', '/portfolio/adults-elegant-red-gold.jpg', { pt: 'Elegante Vermelho e Dourado', es: 'Elegante Rojo y Dorado', en: 'Elegant Red & Gold' }, { pt: 'Folhagem, glicínias, balões vermelhos e dourados.', es: 'Follaje, glicinas y globos rojos y dorados.', en: 'Foliage, wisteria and red and gold balloons.' }, 'adults'),
  item('kids-boys-farm-theme-1st-birthday-pietro', '/portfolio/kids-boys-farm-theme-1st-birthday-pietro.jpg', { pt: 'Fazendinha 1 Aninho', es: 'Granjita 1 Añito', en: 'Farm Theme 1st Birthday' }, { pt: 'Celeiro, cavalinho, feno e balões em tons naturais.', es: 'Granero, caballito, heno y globos en tonos naturales.', en: 'Barn, rocking horse, hay and natural-toned balloons.' }, 'kids'),
  item('kids-boys-lion-safari-1st-birthday-sebastian', '/portfolio/kids-boys-lion-safari-1st-birthday-sebastian.jpg', { pt: 'Safári Leãozinho 1 Aninho', es: 'Safari Leoncito 1 Añito', en: 'Lion Safari 1st Birthday' }, { pt: 'Painéis verde-sálvia, leãozinho e balões coloridos.', es: 'Paneles verde salvia, leoncito y globos coloridos.', en: 'Sage panels, baby lion and colorful balloons.' }, 'kids'),
  item('kids-boys-airplane-1st-birthday-lucca', '/portfolio/kids-boys-airplane-1st-birthday-lucca.jpg', { pt: 'Ursinho Aviador 1 Aninho', es: 'Osito Aviador 1 Añito', en: 'Aviator Bear 1st Birthday' }, { pt: 'Ursinho piloto, nuvens, balão e detalhes azuis.', es: 'Osito piloto, nubes, globo y detalles azules.', en: 'Pilot bear, clouds, balloon and blue details.' }, 'kids'),
  item('kids-boys-baby-shower-blue-clouds-nathan', '/portfolio/kids-boys-baby-shower-blue-clouds-nathan.jpg', { pt: 'Chá de Bebê Azul e Nuvens', es: 'Baby Shower Azul y Nubes', en: 'Blue Clouds Baby Shower' }, { pt: 'Bolo com ursinho, nuvens e detalhes azuis e dourados.', es: 'Pastel con osito, nubes y detalles azules y dorados.', en: 'Teddy bear cake, clouds and blue and gold details.' }, 'kids'),
  item('kids-boys-captain-america-5th-birthday-abraham', '/portfolio/kids-boys-captain-america-5th-birthday-abraham.jpg', { pt: 'Capitão América 5 Anos', es: 'Capitán América 5 Años', en: 'Captain America 5th Birthday' }, { pt: 'Painel azul, escudo, número 5 e balões vermelhos.', es: 'Panel azul, escudo, número 5 y globos rojos.', en: 'Blue panel, shield, number 5 and red balloons.' }, 'kids'),
  item('kids-boys-dinosaur-3rd-birthday-nathan', '/portfolio/kids-boys-dinosaur-3rd-birthday-nathan.jpg', { pt: 'Dinossauro 3 Anos', es: 'Dinosaurio 3 Años', en: 'Dinosaur 3rd Birthday' }, { pt: 'Balões verde, laranja e marrom com tema Three-Rex.', es: 'Globos verdes, naranjas y marrones con tema Three-Rex.', en: 'Green, orange and brown balloons with a Three-Rex theme.' }, 'kids'),
  item('kids-girls-pink-birthday-9yo', '/portfolio/kids-girls-pink-birthday-9yo.jpg', { pt: 'Rosa com Laço 9 Anos', es: 'Rosa con Lazo 9 Años', en: 'Pink Bow 9th Birthday' }, { pt: 'Painéis rosa, laço de veludo, balões e flores.', es: 'Paneles rosa, lazo de terciopelo, globos y flores.', en: 'Pink panels, velvet bow, balloons and flowers.' }, 'kids'),
  item('kids-girls-snow-white-2nd-birthday', '/portfolio/kids-girls-snow-white-2nd-birthday.jpg', { pt: 'Branca de Neve 2 Anos', es: 'Blancanieves 2 Años', en: 'Snow White 2nd Birthday' }, { pt: 'Doces temáticos, cogumelos, número 2 e balões.', es: 'Dulces temáticos, hongos, número 2 y globos.', en: 'Themed sweets, mushrooms, number 2 and balloons.' }, 'kids'),
  item('kids-girls-strawberry-1st-birthday', '/portfolio/kids-girls-strawberry-1st-birthday.jpg', { pt: 'Morango 1 Aninho', es: 'Fresa 1 Añito', en: 'Strawberry 1st Birthday' }, { pt: 'Painel rosa, morangos, xadrez e bolo temático.', es: 'Panel rosa, fresas, cuadros y pastel temático.', en: 'Pink panel, strawberries, gingham and themed cake.' }, 'kids'),
  item('kids-girls-sweet-shop-theme', '/portfolio/kids-girls-sweet-shop-theme.jpg', { pt: 'Doceria', es: 'Dulcería', en: 'Sweet Shop Theme' }, { pt: 'Fachada rosa, toldo listrado, bolo e balões pastel.', es: 'Fachada rosa, toldo rayado, pastel y globos pastel.', en: 'Pink shop facade, striped awning, cake and pastel balloons.' }, 'kids'),
  item('kids-girls-farm-theme-1st-birthday', '/portfolio/kids-girls-farm-theme-1st-birthday.jpg', { pt: 'Fazendinha Rosa 1 Aninho', es: 'Granjita Rosa 1 Añito', en: 'Pink Farm 1st Birthday' }, { pt: 'Celeiro rosa, xadrez, feno e bolo com bichinhos.', es: 'Granero rosa, cuadros, heno y pastel con animalitos.', en: 'Pink barn, gingham, hay and animal cake.' }, 'kids'),
  item('kids-girls-mermaid-theme', '/portfolio/kids-girls-mermaid-theme.jpg', { pt: 'Sereia', es: 'Sirena', en: 'Mermaid Theme' }, { pt: 'Painéis azuis, cauda de sereia e balões pastel.', es: 'Paneles azules, cola de sirena y globos pastel.', en: 'Blue panels, mermaid tail and pastel balloons.' }, 'kids'),
]
